/* ---------========== BÀI HỌC =========------------ */
export const LAY_DANH_SACH_BAI_HOC_PHAN_TRANG = "LAY_DANH_SACH_BAI_HOC_PHAN_TRANG";
export const LAY_DANH_SACH_BAI_HOC_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_BAI_HOC_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_BAI_HOC_PHAN_TRANG_THAT_BAI = "LAY_DANH_SACH_BAI_HOC_PHAN_TRANG_THAT_BAI";

export const LAY_DANH_SACH_BAI_HOC = "LAY_DANH_SACH_BAI_HOC";
export const LAY_DANH_SACH_BAI_HOC_THANH_CONG = "LAY_DANH_SACH_BAI_HOC_THANH_CONG";
export const LAY_DANH_SACH_BAI_HOC_THAT_BAI = "LAY_DANH_SACH_BAI_HOC_THAT_BAI";

export const THEM_MOI_BAI_HOC = "THEM_MOI_BAI_HOC";

export const CAP_NHAT_BAI_HOC = "CAP_NHAT_BAI_HOC";

export const XOA_BAI_HOC = "XOA_BAI_HOC";