/* ---------========== CHƯƠNG HỌC =========------------ */
export const LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG = "LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG";
export const LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG_THAT_BAI = "LAY_DANH_SACH_CHUONG_HOC_PHAN_TRANG_THAT_BAI";

export const LAY_DANH_SACH_CHUONG_HOC = "LAY_DANH_SACH_CHUONG_HOC";
export const LAY_DANH_SACH_CHUONG_HOC_THANH_CONG = "LAY_DANH_SACH_CHUONG_HOC_THANH_CONG";
export const LAY_DANH_SACH_CHUONG_HOC_THAT_BAI = "LAY_DANH_SACH_CHUONG_HOC_THAT_BAI";

export const THEM_MOI_CHUONG_HOC = "THEM_MOI_CHUONG_HOC";

export const CAP_NHAT_CHUONG_HOC = "CAP_NHAT_CHUONG_HOC";
export const CAP_NHAT_CHUONG_HOC_THANH_CONG = "CAP_NHAT_CHUONG_HOC_THANH_CONG";

export const XOA_CHUONG_HOC = "XOA_CHUONG_HOC";
export const XOA_CHUONG_HOC_THANH_CONG = "XOA_CHUONG_HOC_THANH_CONG";