/* ---------========== KHÁCH HÀNG =========------------ */
export const KHACH_HANG_PHAN_TRANG = "KHACH_HANG_PHAN_TRANG";
export const LAY_DANH_SACH_KHACH_HANG_THANH_CONG = "LAY_DANH_SACH_KHACH_HANG_THANH_CONG";
export const LAY_DANH_SACH_KHACH_HANG_THAT_BAI = "LAY_DANH_SACH_KHACH_HANG_THAT_BAI";

export const THEM_MOI_KHACH_HANG = "THEM_MOI_KHACH_HANG";

export const CAP_NHAT_KHACH_HANG = "CAP_NHAT_KHACH_HANG";

export const XOA_KHACH_HANG = "XOA_KHACH_HANG";

export const KHACH_HANG_GHI_DANH_LOP_HOC = "KHACH_HANG_GHI_DANH_LOP_HOC";