/* ---------========== KHÓA HỌC =========------------ */
export const LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG = "LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG";
export const LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG_THAT_BAI = "LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG_THAT_BAI";

export const LAY_DANH_SACH_KHOA_HOC = "LAY_DANH_SACH_KHOA_HOC";
export const LAY_DANH_SACH_KHOA_HOC_THANH_CONG = "LAY_DANH_SACH_KHOA_HOC_THANH_CONG";
export const LAY_DANH_SACH_KHOA_HOC_THAT_BAI = "LAY_DANH_SACH_KHOA_HOC_THAT_BAI";

export const THEM_MOI_KHOA_HOC = "THEM_MOI_KHOA_HOC";

export const CAP_NHAT_KHOA_HOC = "CAP_NHAT_KHOA_HOC";

export const XOA_KHOA_HOC = "XOA_KHOA_HOC";

export const THEM_CHUONG_HOC_VAO_KHOA_HOC = "THEM_CHUONG_HOC_VAO_KHOA_HOC";
export const THEM_CHUONG_HOC_VAO_KHOA_HOC_THANH_CONG = "THEM_CHUONG_HOC_VAO_KHOA_HOC_THANH_CONG";

export const LAY_THONG_TIN_KHOA_HOC_THEO_ID = "LAY_THONG_TIN_KHOA_HOC_THEO_ID";
export const LAY_THONG_TIN_KHOA_HOC_THEO_ID_THANH_CONG = "LAY_THONG_TIN_KHOA_HOC_THEO_ID_THANH_CONG";

export const SAP_XEP_VI_TRI_CHUONG_HOC = "SAP_XEP_VI_TRI_CHUONG_HOC";
export const SAP_XEP_VI_TRI_CHUONG_HOC_THANH_CONG = "SAP_XEP_VI_TRI_CHUONG_HOC_THANH_CONG";