/* ---------========== LỘ TRÌNH =========------------ */
export const LAY_DANH_SACH_LO_TRINH_PHAN_TRANG = "LAY_DANH_SACH_LO_TRINH_PHAN_TRANG";
export const LAY_DANH_SACH_LO_TRINH_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_LO_TRINH_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_LO_TRINH_PHAN_TRANG_THAT_BAI = "LAY_DANH_SACH_LO_TRINH_PHAN_TRANG_THAT_BAI";

export const LAY_DANH_SACH_LO_TRINH = "LAY_DANH_SACH_LO_TRINH";
export const LAY_DANH_SACH_LO_TRINH_THANH_CONG = "LAY_DANH_SACH_LO_TRINH_THANH_CONG";
export const LAY_DANH_SACH_LO_TRINH_THAT_BAI = "LAY_DANH_SACH_LO_TRINH_THAT_BAI";

export const THEM_MOI_LO_TRINH = "THEM_MOI_LO_TRINH";

export const CAP_NHAT_LO_TRINH = "CAP_NHAT_LO_TRINH";

export const XOA_LO_TRINH = "XOA_LO_TRINH";

export const CAP_NHAT_DANH_SACH_KHOA_HOC_CUA_LO_TRINH = "CAP_NHAT_DANH_SACH_KHOA_HOC_CUA_LO_TRINH";
export const CAP_NHAT_DANH_SACH_KHOA_HOC_CUA_LO_TRINH_THANH_CONG = "CAP_NHAT_DANH_SACH_KHOA_HOC_CUA_LO_TRINH_THANH_CONG";

export const LAY_THONG_TIN_LO_TRINH_THEO_ID = "LAY_THONG_TIN_LO_TRINH_THEO_ID";
export const LAY_THONG_TIN_LO_TRINH_THEO_ID_THANH_CONG = "LAY_THONG_TIN_LO_TRINH_THEO_ID_THANH_CONG";

export const SAP_XEP_VI_TRI_KHOA_HOC = "SAP_XEP_VI_TRI_KHOA_HOC";
export const SAP_XEP_VI_TRI_KHOA_HOC_THANH_CONG = "SAP_XEP_VI_TRI_KHOA_HOC_THANH_CONG"; 