/* ---------========== QUYỀN =========------------ */
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG = "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_NGUOI_DUNG_THAT_BAI = "LAY_DANH_SACH_NGUOI_DUNG_THAT_BAI";

export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_THANH_CONG = "LAY_DANH_SACH_NGUOI_DUNG_THANH_CONG";

export const THEM_MOI_NGUOI_DUNG = "THEM_MOI_NGUOI_DUNG";

export const CAP_NHAT_NGUOI_DUNG = "CAP_NHAT_NGUOI_DUNG";

export const XOA_NGUOI_DUNG = "XOA_NGUOI_DUNG";