/* ---------========== NHÓM QUYỀN =========------------ */
export const LAY_DANH_SACH_NHOM_QUYEN_PHAN_TRANG = "LAY_DANH_SACH_NHOM_QUYEN_PHAN_TRANG";
export const LAY_DANH_SACH_NHOM_QUYEN_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_NHOM_QUYEN_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_NHOM_QUYEN_THAT_BAI = "LAY_DANH_SACH_NHOM_QUYEN_THAT_BAI";

export const LAY_DANH_SACH_NHOM_QUYEN = "LAY_DANH_SACH_NHOM_QUYEN";
export const LAY_DANH_SACH_NHOM_QUYEN_THANH_CONG = "LAY_DANH_SACH_NHOM_QUYEN_THANH_CONG";

export const THEM_MOI_NHOM_QUYEN = "THEM_MOI_NHOM_QUYEN";

export const CAP_NHAT_NHOM_QUYEN = "CAP_NHAT_NHOM_QUYEN";

export const XOA_NHOM_QUYEN = "XOA_NHOM_QUYEN";