/* ---------========== QUYỀN =========------------ */
export const QUYEN_PHAN_TRANG = "QUYEN_PHAN_TRANG";
export const LAY_DANH_SACH_QUYEN_PHAN_TRANG_THANH_CONG = "LAY_DANH_SACH_QUYEN_PHAN_TRANG_THANH_CONG";
export const LAY_DANH_SACH_QUYEN_THAT_BAI = "LAY_DANH_SACH_QUYEN_THAT_BAI";

export const LAY_DANH_SACH_QUYEN = "LAY_DANH_SACH_QUYEN";
export const LAY_DANH_SACH_QUYEN_THANH_CONG = "LAY_DANH_SACH_QUYEN_THANH_CONG";

export const THEM_MOI_QUYEN = "THEM_MOI_QUYEN";

export const CAP_NHAT_QUYEN = "CAP_NHAT_QUYEN";

export const XOA_QUYEN = "XOA_QUYEN";