/* ---------========== THÔNG BÁO =========------------ */
export const THONG_BAO_THEM_MOI_THANH_CONG = "THONG_BAO_THEM_MOI_THANH_CONG";
export const THONG_BAO_THEM_MOI_THAT_BAI = "THONG_BAO_THEM_MOI_THAT_BAI";

export const THONG_BAO_CAP_NHAT_THANH_CONG = "THONG_BAO_CAP_NHAT_THANH_CONG";
export const THONG_BAO_CAP_NHAT_THAT_BAI = "THONG_BAO_CAP_NHAT_THAT_BAI";

export const THONG_BAO_XOA_THANH_CONG = "THONG_BAO_XOA_THANH_CONG";
export const THONG_BAO_XOA_THAT_BAI = "THONG_BAO_XOA_THAT_BAI";